input: /scratch/antwerpen/209/vsc20958/Metatropics_runs/TEST_RUN/Input/mpox.csv
outdir: /scratch/antwerpen/209/vsc20958/Metatropics_runs/TEST_RUN/Output
Human_host_fasta: /scratch/antwerpen/209/vsc20958/Metatropics_runs/Metatropics/Databases/Human/chm13v2.0.fa
#Other_host_fasta: /data/Daan/Projects/Metatropics/Databases/Monkeys/AloCar_genomic.fna
dbmeta: /scratch/antwerpen/209/vsc20958/Metatropics_runs/Metatropics/Databases/ViralRefseq
minLength: 200
pair: true
front: 30
tail: 30
minVirus: 0.01
quality: 20 # You can adapt this to '30' to reach Illumina quality
depth: 20 # When wanting high-quality genomes better adapt this to '20"
agreement: 0.8
horizontal_coverage: 5
rcoverage_figure: true

# Rarefaction parameters
perform_rarefaction: true # Preferably rarefy to a reasonable number of input to decrease time of analysis
target_bases: 500000000

# Cleanup module
enable_docker_cleanup: false
